network:
  version: 2
  renderer: networkd
  ethernets:
    ens160:
      addresses:
        - 192.168.0.201/24
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      routes:
        - to: default
          via: 192.168.0.1