name: Build docker images and push to ECR

on:
  push:
    branches:
      - REPLACE_BRANCH_NAME
    paths:
      - REPLACE_PATH # ex: tinc/**

jobs:
  push_to_ecr:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: milvus-tinc
          IMAGE_TAG: ${{ github.sha }}
          WORKING_DIR: tinc
        run: |
          docker build -f $WORKING_DIR/Dockerfile $WORKING_DIR -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
